name = "TutorialsForDevelopers"
uuid = "461d0293-73c3-43f5-880d-c4b30eb7d9f7"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
